### PR TITLE
parallelize glitch project

### PR DESCRIPTION
**Pull request by EthanMarx**
1. Separates training and testing set runs into separate directories for ease of mind
2. Utilizes mldatafind `find_data` when querying strain
3. Adds `analyze_testing_set` flag 
4. Parallelizes pyomicron condor dag generation jobs using a `ProcessPool`
5. Allows querying glitches from multiple segments (i.e. distinct trigger files) for larger datasets

### CODE REVIEW

**Comment by alecgunny** [comment]
Just to make sure, this is still subject to the issues outlined in #198 ? (Not that that would hold this up, since this is valuable in its own right, just clarifying)

**Comment by EthanMarx** [comment]
> Just to make sure, this is still subject to the issues outlined in #198 ? (Not that that would hold this up, since this is valuable in its own right, just clarifying)

Unfortunately yes. Will have to wait to hear back from omicron developers.

**Comment by alecgunny** [comment]
Sounds good, this is great either way

**Review by alecgunny — APPROVED** [review]
The one thing I'll say is that since the pool is just being used to execute subprocesses, you're probably better off using a thread pool, but up to you. Otherwise looks good to me

**Pull request merged**
