### PR TITLE
Fixing bugs in vizapp

### PR DESCRIPTION
**Pull request by alecgunny**
I've started to apply some of the changes outlined by #290 , but there's still lots that needs to be done
- [x]  Refactor sensitive volume calculation and debug why initialization takes so long
- [x] Move `redshift` calculation to initialization of `Foreground` object as one of its attributes
- [ ] Make points on VT plot more visible

### CODE REVIEW

**Comment by alecgunny** [comment]
Moved the `redshift` computation to the front of the VT calculation loop, but this still takes long enough that we won't want it to be done every time we change our mass distribution, so it should probably be moved to the `Foreground` initialization to pay the cost once fully up front.

@EthanMarx I know we talked about some other fixes/additions we would like the vizapp to have yesterday but I can't seem to think of them now. Any additional to-do's this PR should have?

**Comment by EthanMarx** [comment]
I don't think anything for this PR. I'll open up issues for the other items.

**Comment by EthanMarx** [comment]
Should we get these bug fixes merged in and address the other points separately?

**Comment by alecgunny** [comment]
Yeah I think so, having this be so slow is a real bummer when you have some results you want to analyze

**Comment by EthanMarx** [comment]
I think this just needs to be rebased on main to pull the `isort` update

**Comment by alecgunny** [comment]
Yeah I have a couple more slight optimizations I've made locally, I'll get things fixed and then push to get this merged ASAP

**Review by wbenoit26 — APPROVED** [review]

**Pull request merged**
