### PR TITLE
Cleaning up/structuring analysis code

### PR DESCRIPTION
**Pull request by alecgunny**
partially addressing #32

### CODE REVIEW

**Comment by alecgunny** [comment]
- [ ] unit tests
- [ ] leaky integrator
- [ ] outlier rejection

**Comment by alecgunny** [comment]
Restructuring notes:
- [ ] get rid of `parallelize` wrapper and use a custom `AsyncExecutor(num_procs, thread=True)` object that manages either a `ThreadPoolExecutor` or `ProcessPoolExecutor` depending on the value of the `thread` kwarg and is basically the same except the context calls `.shutdown(wait=True, cancel_futures=True)`. Use this manually in `analyze_o2` as a context in the `main` function that gets passed as an arg to `build_background`.
- [ ] Thread segment loading via `.map` and run `analyze_segment` on the loaded segments with multiple values of `norm_seconds` via process pool. Use `.add_done_callback` with a lambda to write results explicitly to `${root}/{norm_seconds}/{shift}/{fname}.gwf`. Get rid of `write_dir` option in `analyze_segment`
- [ ] Build `integrator` and `normalizer` submodules of `bbhnet.analysis` that implement other integration and normalization schemes as callables with fixed calling syntax, add these as kwargs to `analyze_segment` with `boxcar_filter` and a new `GaussianNormalizer(norm_seconds=None)` as defaults.

**Comment by alecgunny** [comment]
How can we leverage the gwpy [`SegmentList`](https://gwpy.github.io/docs/stable/api/gwpy.segments.SegmentList/#gwpy.segments.SegmentList) object here to simplify the task of generating segments?

**Comment by alecgunny** [comment]
Should we change the organize the timeslides by GPS days in the manner used in #18 instead of the seemingly arbitrary "runs" utilized on the O2 data?

**Comment by alecgunny** [comment]
Remaining tasks before opening for revieew:
- [ ] `bbhnet.io.h5` unit tests
- [ ] Reshape expected timeslide directory structure to get rid of "runs"
- [ ] Fill out `bbhnet.io.timeslides` unit tests
- [ ] Finish `bbhnet.analysis` unit tests
- [ ] Tests for `projects/o2-timeslides-analysis`
- [ ] Delete notebook from `projects/o2-timeslides-analysis` or restructure to use new code

Issues to open once this is merged
- [ ] Implement leaky integrator
- [ ] Implement normalizer with outlier rejection

**Comment by alecgunny** [comment]
@rafia17 it looks like your PR might have gotten a little tangled up with all the changes that have been going on with both the `main` branch and this PR in parallel. Since I think it makes sense to get this code merged in ASAP, and since I think having it all in `main` will make developing additions to it in parallel simpler, here is what I propose @EthanMarx : 
- I'll fix the merge conflict in `ci-tests.yaml`. Once this passes CI and I get your review, I will merge it _without_ Rafia's h5 unit tests
- I'll open issues for both these unit tests as well as unit tests for the `o2-timeslide-analysis` project (and feature enhancement issues for the leaky integrator and outlier reject normalizers)
- @rafia17, once this is merged, you can `git checkout main; git pull main`, then `git checkout -b h5-tests` to make a new branch to submit as a PR directly to this repo. You can then checkout _just_ your test file from your old branch, `git checkout analysis-io-tests libs/io/tests/test_h5.py; git add libs/io/tests/test_h5.py; git commit -am "adding h5 tests"`
- You can then submit this branch as a PR to this repo, and link it to the unit tests issue that I'll open up so that when the PR gets merged, that issue will be closed.

Does this sound acceptable to everyone?

**Comment by rafia17** [comment]
Sounds good to me

**Review by EthanMarx — APPROVED** [review]
A lot of content in here but looks good. I have a few questions about the logic of the parallelization, for my own sake. Also still haven't fully wrapped my head around the structures of the Segment / Timeslides objects, but I figure thats because I havent really dove into those directories / how bbhnet performs timeslides.  

In any case looks good and we can go over these in the meeting or something.

**Pull request merged**
